[package]
name = "paillier"
version = "0.1.0"
authors = ["Morten Dahl"]
description = "A pure-Rust implementation of the Paillier encryption scheme"
keywords = [
  "Paillier",
  "homomorphic encryption",
  "secure computation",
  "multi-party computation", "MPC",
  "cryptography", "crypto"
]
homepage = "https://github.com/mortendahl/rust-paillier"
repository = "https://github.com/mortendahl/rust-paillier"
license = "MIT"

[features]
default = ["ramp", "num"]
keygen = ["primal"]

[dependencies]
rand = "0.3"
ramp = { version = "0.3", optional = true }
num = { version = "0.1", optional = true }
primal = { version = "0.2", optional = true }
